CREATE TABLE IF NOT EXISTS "user" (
id long  PRIMARY KEY,
name varchar (100),
login varchar (100) NOT NULL,
email varchar (200) NOT NULL,
birthday timestamp
);

CREATE TABLE IF NOT EXISTS "friendship" (
friendship_id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
from_id long REFERENCES "user" (id),
to_id long REFERENCES "user" (id),
friendship_status varchar(20)
);

CREATE TABLE IF NOT EXISTS "rating" (
rating_id int PRIMARY KEY,
rating_name varchar (100) NOT NULL,
rating_description varchar(500)
);


CREATE TABLE IF NOT EXISTS "film" (
id long PRIMARY KEY,
name varchar(100) NOT NULL,
description varchar (200),
release_date timestamp,
duration int,
rating_id int REFERENCES "rating" (rating_id)
);

CREATE TABLE IF NOT EXISTS "genre" (
genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
genre_name varchar(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS "film_genres" (
film_genres_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
film_id long REFERENCES "film" (id),
genre_id int REFERENCES "genre" (genre_id)
);

CREATE TABLE IF NOT EXISTS "likes" (
likes_id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
film_id long REFERENCES "film" (id),
user_id long REFERENCES "user" (id)
);
